In [1]:
!pip install -q torch

In [2]:
import torch
print(torch.__version__)

1.7.0+cu101


# Back Propagation
y=x^2

In [11]:
x = torch.tensor(4.0, requires_grad=True)
x

tensor(4., requires_grad=True)

In [12]:
y = x**2

In [13]:
#BackPropagation of y = 2*x
y.backward()
print(x.grad)

tensor(8.)


In [14]:
a = [[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]]
a

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [16]:
aList = torch.tensor(a, requires_grad=True)
aList

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], requires_grad=True)

In [17]:
# y = x**3 + x**2
y = aList**3 + aList**2

In [18]:
y

tensor([[  2.,  12.,  36.],
        [ 80., 150., 252.],
        [392., 576., 810.]], grad_fn=<AddBackward0>)

In [19]:
z = y.sum()
z

tensor(2310., grad_fn=<SumBackward0>)

In [20]:
z.backward()

In [21]:
z

tensor(2310., grad_fn=<SumBackward0>)

In [22]:
aList.grad

tensor([[  5.,  16.,  33.],
        [ 56.,  85., 120.],
        [161., 208., 261.]])